### ISSUE TITLE
Cyclic import

### ISSUE THREAD

**Issue by artmakarov** [VirtoCommerce/vc-odt-mpa-theme#133]
Cyclical dependence in imports:

**1.** 
https://github.com/VirtoCommerce/vc-odt-mpa-theme/blob/e605306dbbbfb7a445e5ab0bd19b349737b72ef9/client-app/src/core/models/search/extensions/cart-search-query.ts#L3
https://github.com/VirtoCommerce/vc-odt-mpa-theme/blob/e605306dbbbfb7a445e5ab0bd19b349737b72ef9/client-app/src/core/models/search/extensions/cart-search-criteria.ts#L2

**2.** 
https://github.com/VirtoCommerce/vc-odt-mpa-theme/blob/e605306dbbbfb7a445e5ab0bd19b349737b72ef9/client-app/src/core/models/search/extensions/order-search-query.ts#L3
https://github.com/VirtoCommerce/vc-odt-mpa-theme/blob/e605306dbbbfb7a445e5ab0bd19b349737b72ef9/client-app/src/core/models/search/extensions/order-search-criteria.ts#L2

**...** 

and in other files in the folder `client-app/src/core/models/search/extensions`

**Why did you use `prototype` to extend the class?**

**Comment by lnetrebskii** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-3321 has been created

**Comment by asvishnyakov** [comment]
1. Where is no actual cyclic dependencies.
Yes, for example, criteria files import query files and vers a vers. But actually it doesn’t import any classes, cart-search-query import default endpoint of cart-search-criteria:
import 'core/models/search/extensions/cart-search-criteria';
what’s mean only extensions for search criteria will be imported, i.e.:

```typescript
declare module '@core/api/api-clients' {
  interface CartSearchCriteria extends KeywordSearchCriteria {
    keyword?: string;
    toSearchQuery<TSearchQuery extends CartSearchQuery>(searchQueryType: new() => TSearchQuery): TSearchQuery;
    normalize(): void;
  }
}
```

2.

> Why did you use prototype to extend the class?

Because there is no other way to make inheritance here: alternative is a massive duplication in services code or duplication of model. The main problem is what API schema and generator tools doesn’t produce inheritance code for models, i.e. if you have CartSearchCriteria inherited from PaginatedSearchCriteria in storefront, they are separate models with properties duplication in generated code. That’s because in both API schema & code generators inheritance is opt-in experiment feature.
